#!/usr/bin/env python3

import argparse
import time
from pathlib import Path

import numpy as np
import viser


# ============================================================
# BINARY PLY READER
# Compatible with the binary PLY files generated by your pipeline.
# ============================================================

PLY_TYPES = {
    "char": "i1",
    "int8": "i1",
    "uchar": "u1",
    "uint8": "u1",
    "short": "<i2",
    "int16": "<i2",
    "ushort": "<u2",
    "uint16": "<u2",
    "int": "<i4",
    "int32": "<i4",
    "uint": "<u4",
    "uint32": "<u4",
    "float": "<f4",
    "float32": "<f4",
    "double": "<f8",
    "float64": "<f8",
}


def read_ply_header(path):
    """Read the binary PLY header and return its vertex information."""

    with open(path, "rb") as f:
        if f.readline().decode("ascii").strip() != "ply":
            raise ValueError("This file is not a valid PLY file.")

        file_format = None
        vertex_count = None
        vertex_properties = []
        current_element = None

        while True:
            raw_line = f.readline()

            if not raw_line:
                raise ValueError("PLY header ended before end_header.")

            line = raw_line.decode("ascii").strip()

            if not line or line.startswith(("comment ", "obj_info ")):
                continue

            fields = line.split()

            if fields[0] == "format":
                file_format = fields[1]

            elif fields[0] == "element":
                current_element = fields[1]

                if current_element == "vertex":
                    vertex_count = int(fields[2])

            elif fields[0] == "property" and current_element == "vertex":
                if fields[1] == "list":
                    raise ValueError("List properties are not supported.")

                type_name, property_name = fields[1], fields[2]

                if type_name not in PLY_TYPES:
                    raise ValueError(
                        f"Unsupported PLY property type: {type_name}"
                    )

                vertex_properties.append(
                    (property_name, PLY_TYPES[type_name])
                )

            elif fields[0] == "end_header":
                data_offset = f.tell()
                break

    if file_format != "binary_little_endian":
        raise ValueError(
            f"Unsupported format: {file_format}. "
            "Expected binary_little_endian."
        )

    if vertex_count is None or vertex_count < 0:
        raise ValueError("Invalid PLY vertex count.")

    vertex_dtype = np.dtype(vertex_properties)

    return vertex_count, vertex_dtype, data_offset


def load_ply(path, max_points=500_000):
    """Load XYZ and RGB, optionally sampling large point clouds."""

    path = Path(path)

    if not path.is_file():
        raise FileNotFoundError(f"PLY file not found: {path}")

    count, dtype, offset = read_ply_header(path)

    expected_bytes = count * dtype.itemsize
    actual_bytes = path.stat().st_size - offset

    if actual_bytes < expected_bytes:
        raise ValueError(
            f"PLY data is truncated: expected {expected_bytes:,} bytes, "
            f"found {actual_bytes:,}."
        )

    vertices = np.memmap(
        path,
        dtype=dtype,
        mode="r",
        offset=offset,
        shape=(count,),
    )

    fields = set(vertices.dtype.names or ())
    required = {"x", "y", "z"}

    if not required.issubset(fields):
        raise ValueError(
            f"PLY requires x, y, z fields. Found: {sorted(fields)}"
        )

    # Randomly sample for browser performance, without changing the PLY.
    if max_points > 0 and count > max_points:
        rng = np.random.default_rng(42)
        indices = np.sort(
            rng.choice(count, size=max_points, replace=False)
        )
        vertices = vertices[indices]

    points = np.column_stack(
        (vertices["x"], vertices["y"], vertices["z"])
    ).astype(np.float32)

    if {"red", "green", "blue"}.issubset(fields):
        colors = np.column_stack(
            (vertices["red"], vertices["green"], vertices["blue"])
        ).astype(np.uint8)
    else:
        print("No RGB fields found; using gray.")
        colors = np.full((len(points), 3), 180, dtype=np.uint8)

    valid = np.isfinite(points).all(axis=1)
    points = points[valid]
    colors = colors[valid]

    if len(points) == 0:
        raise ValueError("No finite 3D points found in the PLY.")

    print("\n" + "=" * 60)
    print("POINT CLOUD")
    print("=" * 60)
    print(f"File: {path.resolve()}")
    print(f"Vertices in file: {count:,}")
    print(f"Points displayed: {len(points):,}")
    print(f"XYZ minimum: {points.min(axis=0)}")
    print(f"XYZ maximum: {points.max(axis=0)}")
    print("=" * 60)

    return points, colors


# ============================================================
# VISER VIEWER
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        description="Visualize a colored PLY point cloud with Viser."
    )

    parser.add_argument("ply", type=Path, help="Path to the PLY file")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8080)
    parser.add_argument("--max-points", type=int, default=500_000)
    parser.add_argument(
        "--point-size",
        type=float,
        default=None,
        help="Override automatic point size.",
    )

    args = parser.parse_args()

    if not 1 <= args.port <= 65535:
        parser.error("Port must be between 1 and 65535.")

    if args.max_points < 0:
        parser.error("--max-points must be non-negative.")

    if args.point_size is not None and args.point_size <= 0:
        parser.error("--point-size must be positive.")

    points, colors = load_ply(args.ply, args.max_points)

    # Estimate scene scale for sensible camera positioning.
    lower = np.percentile(points, 2, axis=0)
    upper = np.percentile(points, 98, axis=0)

    center = (lower + upper) / 2.0
    extent = float(np.max(upper - lower))

    if not np.isfinite(extent) or extent < 1e-6:
        lower = points.min(axis=0)
        upper = points.max(axis=0)
        center = (lower + upper) / 2.0
        extent = float(np.max(upper - lower))

    if not np.isfinite(extent) or extent < 1e-6:
        extent = 1.0

    point_size = (
        args.point_size
        if args.point_size is not None
        else max(extent * 0.001, 1e-4)
    )

    # Start the server on all interfaces for cluster port forwarding.
    server = viser.ViserServer(
        host=args.host,
        port=args.port,
        label=f"Point cloud: {args.ply.name}",
    )

    server.scene.set_up_direction("+z")
    server.scene.world_axes.visible = True

    direction = np.array([1.0, -1.0, 0.8])
    direction /= np.linalg.norm(direction)

    server.initial_camera.position = center + direction * extent * 2.5
    server.initial_camera.look_at = center
    server.initial_camera.far = max(1000.0, extent * 20.0)
    server.initial_camera.near = max(1e-5, extent * 1e-5)

    server.scene.add_point_cloud(
        name="/semantic_point_cloud",
        points=points,
        colors=colors,
        point_size=point_size,
        point_shape="circle",
        precision="float32",
    )

    # Log WebSocket connection changes.
    @server.on_client_connect
    def on_connect(client):
        print(
            f"[CONNECTED] Client {client.client_id}; "
            f"active clients: {len(server.get_clients())}"
        )

    @server.on_client_disconnect
    def on_disconnect(client):
        print(
            f"[DISCONNECTED] Client {client.client_id}; "
            f"active clients: {len(server.get_clients())}"
        )

    print("\nViser server started.")
    print(f"Listening on: {args.host}:{args.port}")
    print(f"Point size: {point_size:.6g}")
    print(f"Camera target: {center}")
    print(f"Camera distance: {extent * 2.5:.4g}")
    print("\nIMPORTANT:")
    print("For JupyterHub, use your platform's port proxy URL.")
    print(f"The port to forward is {args.port}.")
    print("Do not open localhost in your personal browser unless")
    print("you have established an SSH tunnel.")
    print("\nKeep this process running. Press Ctrl+C to stop.")

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\nStopping viewer...")
    finally:
        server.stop()


if __name__ == "__main__":
    main()